name: afake_invoice
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.0.3
  http: ^0.13.5
  lottie: ^1.4.3
  dropdown_button2: ^1.9.2
  conditional_builder_null_safety: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: AJ Regular
      fonts:
        - asset: assets/fonts/AJ-REGULAR.TTF
          weight: 700
